"""Audit store: content-addressed artifacts, commitments, independent recompute.

The honesty backbone of vidaio-next: every
scored metric must be independently recomputable by third parties from what
this module preserves — inputs, outputs, manifests, score packets, weight
vectors — pinned by digests that are committed on chain before enrollment and
published after evaluation. Configuration section: `audit` (see config.py).
"""

from vidaio.audit.bundle import (
    AuditBundle,
    CompetitionItemBinding,
    LifecycleStage,
    build_bundle,
)
from vidaio.audit.canonical import canonical_json_bytes, sha256_hex
from vidaio.audit.commitments import (
    ALLOWED_COMMITMENT_KINDS,
    COMMITMENT_DOMAIN,
    CommitmentLedger,
    CommitmentPayload,
    CommitmentStatus,
    CompetitionCommitment,
    LedgerIntegrityError,
    load_competition_commitment,
    pin_git_sha,
    PublicationRecord,
    build_competition_commitment,
    build_publication_record,
    reward_parameter_digest,
    merkle_proof,
    merkle_root,
    verify_merkle_proof,
)
from vidaio.audit.config import AuditConfig
from vidaio.audit.recompute import (
    ARTIFACT_CORRUPT,
    ARTIFACT_MISSING,
    BACKEND_VERSION_MISMATCH,
    COMMITMENT_MISMATCH,
    DEFAULT_TOLERANCES,
    DIGEST_MISMATCH,
    IDENTITY_MISMATCH,
    INCOMPLETE_BUNDLE,
    MALFORMED_SCORE_PACKET,
    MERKLE_EXCLUSION,
    METRIC_SET_MISMATCH,
    MISSING_ANCHOR,
    PACKET_INCONSISTENT,
    RECOMPUTE_ERROR,
    REVEAL_INVALID,
    REVEAL_UNVERIFIED,
    SCORE_MISMATCH,
    SCORER_VERSION_MISMATCH,
    CheckResult,
    RecomputedScore,
    ScorePacketShape,
    ScoreRecomputer,
    StaticRecomputer,
    VerificationReport,
    verify_bundle,
)
from vidaio.audit.store import (
    AesGcmEnvelope,
    ArtifactTooLargeError,
    FINALIZED_MARKER,
    SEALED_KINDS,
    ArtifactKind,
    ArtifactRef,
    AuditStore,
    Envelope,
    HippiusStore,
    IntegrityError,
    LocalFsStore,
    NotConfiguredError,
    PassthroughEnvelope,
    ReadOnlyStoreError,
    SealedArtifactAccessError,
    S3Store,
    SetAlreadyFinalizedError,
    SetNotFinalizedError,
    WriteOnceConflictError,
    backend_key,
    finalized_marker_key,
    make_store,
    make_public_store,
    make_unsealed_writer_store,
    released_backend_key,
    set_member_key,
)

__all__ = [
    # config
    "AuditConfig",
    # store
    "ArtifactKind",
    "ArtifactRef",
    "AuditStore",
    "LocalFsStore",
    "S3Store",
    "HippiusStore",
    "make_store",
    "make_public_store",
    "make_unsealed_writer_store",
    "backend_key",
    "released_backend_key",
    "Envelope",
    "AesGcmEnvelope",
    "PassthroughEnvelope",
    "SEALED_KINDS",
    "IntegrityError",
    "NotConfiguredError",
    "ReadOnlyStoreError",
    "SealedArtifactAccessError",
    "ArtifactTooLargeError",
    # object-store set convention (_FINALIZED half-write guard)
    "FINALIZED_MARKER",
    "set_member_key",
    "finalized_marker_key",
    "SetNotFinalizedError",
    "SetAlreadyFinalizedError",
    "WriteOnceConflictError",
    # bundle
    "AuditBundle",
    "CompetitionItemBinding",
    "LifecycleStage",
    "build_bundle",
    # commitments
    "ALLOWED_COMMITMENT_KINDS",
    "COMMITMENT_DOMAIN",
    "LedgerIntegrityError",
    "load_competition_commitment",
    "CompetitionCommitment",
    "pin_git_sha",
    "PublicationRecord",
    "CommitmentPayload",
    "build_competition_commitment",
    "build_publication_record",
    "reward_parameter_digest",
    "merkle_root",
    "merkle_proof",
    "verify_merkle_proof",
    "CommitmentLedger",
    "CommitmentStatus",
    # recompute
    "ScoreRecomputer",
    "RecomputedScore",
    "ScorePacketShape",
    "StaticRecomputer",
    "CheckResult",
    "VerificationReport",
    "verify_bundle",
    "DEFAULT_TOLERANCES",
    "SCORE_MISMATCH",
    "ARTIFACT_CORRUPT",
    "ARTIFACT_MISSING",
    "BACKEND_VERSION_MISMATCH",
    "COMMITMENT_MISMATCH",
    "DIGEST_MISMATCH",
    "IDENTITY_MISMATCH",
    "INCOMPLETE_BUNDLE",
    "MALFORMED_SCORE_PACKET",
    "MERKLE_EXCLUSION",
    "METRIC_SET_MISMATCH",
    "MISSING_ANCHOR",
    "PACKET_INCONSISTENT",
    "RECOMPUTE_ERROR",
    "REVEAL_INVALID",
    "REVEAL_UNVERIFIED",
    "SCORER_VERSION_MISMATCH",
    # canonical helpers
    "canonical_json_bytes",
    "sha256_hex",
]
