"""Versioned schema-v14 baselines promoted from current-schema CROWN evidence.

Both tracks start from an archived public v0 implementation.  Serving state is
independent of the finite reward window: it changes only through the verified,
idempotent CROWN pipeline or an explicit append-only baseline rollback.
Historical schema-v13 tables remain readable for migration diagnostics, but their
candidate-selected write path is deliberately not exported and fails closed.
"""

from vidaio.registry.competition_source import (
    COMPETITION_MIGRATIONS_DIR,
    CompetitionFacts,
    CompetitionSource,
    ItemLinkage,
    SqliteCompetitionSource,
    WinnerFacts,
)
from vidaio.registry.baseline import (
    SUPPORTED_TRACKS,
    BaselineRecord,
    BaselineRegistryError,
    BaselineRollbackError,
    GenesisBaseline,
    GenesisBaselineError,
    PendingPromotionError,
    PromotionLatch,
    baseline_events,
    baseline_history,
    baseline_invariant_violations,
    baseline_version,
    current_baseline,
    pending_promotion,
    promotion_latch_by_key,
    require_no_pending_promotion,
    rollback_baseline,
    seed_genesis_baselines,
    verify_baseline_invariants,
)
from vidaio.registry.baseline_promotion import (
    CROWN_EPOCH_SCHEMA_VERSION,
    BaselineBuildError,
    BaselineBuildRunner,
    BaselinePromotionPipeline,
    BaselineRerunResult,
    CrownArchiveError,
    CrownEpochNotVerifiedError,
    CrownProofMismatchError,
    CrownPromotionError,
    ForeignEpochSchemaError,
    NonCrownEpochError,
)
from vidaio.registry.crown_source import (
    CrownAuditItem,
    VerifiedCrownEpoch,
    VerifiedCrownEpochSource,
)
from vidaio.registry.config import (
    REGISTRY_HTTP_PORT,
    REGISTRY_METRICS_PORT,
    GenesisBaselineConfig,
    RegistryConfig,
    production_registry_problems,
)
from vidaio.registry.registry import (
    ChampionRecord,
    LegacyRegistryWriteDisabledError,
    RegistryError,
    active_invariant_violations,
    current,
    get_version,
    history,
    list_events,
    migrate,
    transaction,
    verify_startup_invariants,
)
from vidaio.registry.serving import BaselineBackend, ChampionBackend
from vidaio.registry.service import (
    REGISTRY_API_KIND,
    REGISTRY_SCHEMA_VERSION,
    BaselinePromotionWatcher,
    BaselineRegistryService,
    RegistryStartupError,
    verify_active_archives,
    verify_genesis_archives,
)

__all__ = [
    "ChampionRecord",
    "ChampionBackend",
    "RegistryError",
    "LegacyRegistryWriteDisabledError",
    "COMPETITION_MIGRATIONS_DIR",
    "CompetitionFacts",
    "CompetitionSource",
    "ItemLinkage",
    "SqliteCompetitionSource",
    "WinnerFacts",
    "migrate",
    "current",
    "get_version",
    "list_events",
    "history",
    "transaction",
    "active_invariant_violations",
    "verify_startup_invariants",
    "REGISTRY_API_KIND",
    "REGISTRY_HTTP_PORT",
    "REGISTRY_METRICS_PORT",
    "REGISTRY_SCHEMA_VERSION",
    "CROWN_EPOCH_SCHEMA_VERSION",
    "SUPPORTED_TRACKS",
    "BaselineBackend",
    "BaselineBuildError",
    "BaselineBuildRunner",
    "BaselinePromotionWatcher",
    "BaselinePromotionPipeline",
    "BaselineRecord",
    "BaselineRegistryService",
    "BaselineRegistryError",
    "BaselineRerunResult",
    "BaselineRollbackError",
    "CrownArchiveError",
    "CrownAuditItem",
    "CrownEpochNotVerifiedError",
    "CrownProofMismatchError",
    "CrownPromotionError",
    "ForeignEpochSchemaError",
    "GenesisBaseline",
    "GenesisBaselineConfig",
    "GenesisBaselineError",
    "NonCrownEpochError",
    "PendingPromotionError",
    "PromotionLatch",
    "RegistryConfig",
    "RegistryStartupError",
    "VerifiedCrownEpoch",
    "VerifiedCrownEpochSource",
    "baseline_events",
    "baseline_history",
    "baseline_invariant_violations",
    "baseline_version",
    "current_baseline",
    "pending_promotion",
    "promotion_latch_by_key",
    "require_no_pending_promotion",
    "rollback_baseline",
    "seed_genesis_baselines",
    "production_registry_problems",
    "verify_active_archives",
    "verify_baseline_invariants",
    "verify_genesis_archives",
]
